# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\gSurf_0.1.2a.ui'
#
# Created: Sat Apr 07 18:32:42 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(998, 708)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "gSurf   -  vers. 0.1.2", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mplwidget = MplWidget(self.centralwidget)
        self.mplwidget.setGeometry(QtCore.QRect(260, 5, 730, 655))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget.sizePolicy().hasHeightForWidth())
        self.mplwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.mplwidget.setFont(font)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.Input_widget = QtGui.QWidget(self.centralwidget)
        self.Input_widget.setGeometry(QtCore.QRect(5, 6, 251, 138))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Input_widget.setFont(font)
        self.Input_widget.setObjectName(_fromUtf8("Input_widget"))
        self.input_groupBox = QtGui.QGroupBox(self.Input_widget)
        self.input_groupBox.setGeometry(QtCore.QRect(10, 5, 236, 128))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.input_groupBox.setFont(font)
        self.input_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Input layers", None, QtGui.QApplication.UnicodeUTF8))
        self.input_groupBox.setObjectName(_fromUtf8("input_groupBox"))
        self.show_label = QtGui.QLabel(self.input_groupBox)
        self.show_label.setGeometry(QtCore.QRect(195, 18, 30, 13))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.show_label.setFont(font)
        self.show_label.setText(QtGui.QApplication.translate("MainWindow", "show", None, QtGui.QApplication.UnicodeUTF8))
        self.show_label.setObjectName(_fromUtf8("show_label"))
        self.layoutWidget = QtGui.QWidget(self.input_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 36, 213, 59))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.show_Fault_checkBox = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.show_Fault_checkBox.setFont(font)
        self.show_Fault_checkBox.setText(_fromUtf8(""))
        self.show_Fault_checkBox.setChecked(True)
        self.show_Fault_checkBox.setObjectName(_fromUtf8("show_Fault_checkBox"))
        self.gridLayout.addWidget(self.show_Fault_checkBox, 1, 2, 1, 1)
        self.Trace_lineEdit = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Trace_lineEdit.setFont(font)
        self.Trace_lineEdit.setReadOnly(True)
        self.Trace_lineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "optional", None, QtGui.QApplication.UnicodeUTF8))
        self.Trace_lineEdit.setObjectName(_fromUtf8("Trace_lineEdit"))
        self.gridLayout.addWidget(self.Trace_lineEdit, 1, 1, 1, 1)
        self.show_DEM_checkBox = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.show_DEM_checkBox.setFont(font)
        self.show_DEM_checkBox.setText(_fromUtf8(""))
        self.show_DEM_checkBox.setChecked(True)
        self.show_DEM_checkBox.setObjectName(_fromUtf8("show_DEM_checkBox"))
        self.gridLayout.addWidget(self.show_DEM_checkBox, 0, 2, 1, 1)
        self.DEM_lineEdit = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DEM_lineEdit.setFont(font)
        self.DEM_lineEdit.setReadOnly(True)
        self.DEM_lineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "required", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_lineEdit.setObjectName(_fromUtf8("DEM_lineEdit"))
        self.gridLayout.addWidget(self.DEM_lineEdit, 0, 1, 1, 1)
        self.Fault_label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Fault_label.setFont(font)
        self.Fault_label.setText(QtGui.QApplication.translate("MainWindow", "Faults", None, QtGui.QApplication.UnicodeUTF8))
        self.Fault_label.setObjectName(_fromUtf8("Fault_label"))
        self.gridLayout.addWidget(self.Fault_label, 1, 0, 1, 1)
        self.DEM_label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DEM_label.setFont(font)
        self.DEM_label.setText(QtGui.QApplication.translate("MainWindow", "DEM", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_label.setObjectName(_fromUtf8("DEM_label"))
        self.gridLayout.addWidget(self.DEM_label, 0, 0, 1, 1)
        self.DEM_cmap_label = QtGui.QLabel(self.input_groupBox)
        self.DEM_cmap_label.setGeometry(QtCore.QRect(10, 103, 95, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DEM_cmap_label.setFont(font)
        self.DEM_cmap_label.setText(QtGui.QApplication.translate("MainWindow", "DEM colormap", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_label.setObjectName(_fromUtf8("DEM_cmap_label"))
        self.DEM_cmap_comboBox = QtGui.QComboBox(self.input_groupBox)
        self.DEM_cmap_comboBox.setGeometry(QtCore.QRect(107, 100, 98, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DEM_cmap_comboBox.setFont(font)
        self.DEM_cmap_comboBox.setObjectName(_fromUtf8("DEM_cmap_comboBox"))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "jet", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "gray", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "bone", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "hot", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "autumn", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "cool", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "copper", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(7, QtGui.QApplication.translate("MainWindow", "hsv", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(8, QtGui.QApplication.translate("MainWindow", "pink", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(9, QtGui.QApplication.translate("MainWindow", "prism", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(10, QtGui.QApplication.translate("MainWindow", "spring", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(11, QtGui.QApplication.translate("MainWindow", "summer", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(12, QtGui.QApplication.translate("MainWindow", "winter", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(13, QtGui.QApplication.translate("MainWindow", "spectral", None, QtGui.QApplication.UnicodeUTF8))
        self.DEM_cmap_comboBox.addItem(_fromUtf8(""))
        self.DEM_cmap_comboBox.setItemText(14, QtGui.QApplication.translate("MainWindow", "flag", None, QtGui.QApplication.UnicodeUTF8))
        self.SourcePoint_widget = QtGui.QWidget(self.centralwidget)
        self.SourcePoint_widget.setGeometry(QtCore.QRect(5, 148, 251, 130))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.SourcePoint_widget.setFont(font)
        self.SourcePoint_widget.setObjectName(_fromUtf8("SourcePoint_widget"))
        self.point_groupBox = QtGui.QGroupBox(self.SourcePoint_widget)
        self.point_groupBox.setGeometry(QtCore.QRect(10, 2, 236, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.point_groupBox.setFont(font)
        self.point_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Plane source point", None, QtGui.QApplication.UnicodeUTF8))
        self.point_groupBox.setObjectName(_fromUtf8("point_groupBox"))
        self.layoutWidget1 = QtGui.QWidget(self.point_groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 124, 74))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Pt_label_x = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Pt_label_x.setFont(font)
        self.Pt_label_x.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.Pt_label_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Pt_label_x.setObjectName(_fromUtf8("Pt_label_x"))
        self.gridLayout_2.addWidget(self.Pt_label_x, 0, 0, 1, 1)
        self.Pt_spinBox_x = QtGui.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Pt_spinBox_x.setFont(font)
        self.Pt_spinBox_x.setMinimum(-1000000000)
        self.Pt_spinBox_x.setMaximum(1000000000)
        self.Pt_spinBox_x.setSingleStep(50)
        self.Pt_spinBox_x.setObjectName(_fromUtf8("Pt_spinBox_x"))
        self.gridLayout_2.addWidget(self.Pt_spinBox_x, 0, 1, 1, 1)
        self.Pt_label_y = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Pt_label_y.setFont(font)
        self.Pt_label_y.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.Pt_label_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Pt_label_y.setObjectName(_fromUtf8("Pt_label_y"))
        self.gridLayout_2.addWidget(self.Pt_label_y, 1, 0, 1, 1)
        self.Pt_spinBox_y = QtGui.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Pt_spinBox_y.setFont(font)
        self.Pt_spinBox_y.setMinimum(-1000000000)
        self.Pt_spinBox_y.setMaximum(1000000000)
        self.Pt_spinBox_y.setSingleStep(50)
        self.Pt_spinBox_y.setObjectName(_fromUtf8("Pt_spinBox_y"))
        self.gridLayout_2.addWidget(self.Pt_spinBox_y, 1, 1, 1, 1)
        self.Pt_label_z = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Pt_label_z.setFont(font)
        self.Pt_label_z.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.Pt_label_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Pt_label_z.setObjectName(_fromUtf8("Pt_label_z"))
        self.gridLayout_2.addWidget(self.Pt_label_z, 2, 0, 1, 1)
        self.Pt_spinBox_z = QtGui.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Pt_spinBox_z.setFont(font)
        self.Pt_spinBox_z.setMinimum(-10000000)
        self.Pt_spinBox_z.setMaximum(10000000)
        self.Pt_spinBox_z.setSingleStep(5)
        self.Pt_spinBox_z.setObjectName(_fromUtf8("Pt_spinBox_z"))
        self.gridLayout_2.addWidget(self.Pt_spinBox_z, 2, 1, 1, 1)
        self.splitter = QtGui.QSplitter(self.point_groupBox)
        self.splitter.setGeometry(QtCore.QRect(145, 42, 86, 64))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.show_SrcPt_checkBox = QtGui.QCheckBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.show_SrcPt_checkBox.setFont(font)
        self.show_SrcPt_checkBox.setText(QtGui.QApplication.translate("MainWindow", "show", None, QtGui.QApplication.UnicodeUTF8))
        self.show_SrcPt_checkBox.setChecked(True)
        self.show_SrcPt_checkBox.setObjectName(_fromUtf8("show_SrcPt_checkBox"))
        self.Z_fix2DEM_checkBox_z = QtGui.QCheckBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Z_fix2DEM_checkBox_z.setFont(font)
        self.Z_fix2DEM_checkBox_z.setText(QtGui.QApplication.translate("MainWindow", "fix  to DEM", None, QtGui.QApplication.UnicodeUTF8))
        self.Z_fix2DEM_checkBox_z.setChecked(True)
        self.Z_fix2DEM_checkBox_z.setObjectName(_fromUtf8("Z_fix2DEM_checkBox_z"))
        self.Plane_widget = QtGui.QWidget(self.centralwidget)
        self.Plane_widget.setGeometry(QtCore.QRect(5, 285, 252, 253))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Plane_widget.setFont(font)
        self.Plane_widget.setObjectName(_fromUtf8("Plane_widget"))
        self.plane_groupBox = QtGui.QGroupBox(self.Plane_widget)
        self.plane_groupBox.setGeometry(QtCore.QRect(10, 5, 237, 242))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.plane_groupBox.setFont(font)
        self.plane_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Plane attitude", None, QtGui.QApplication.UnicodeUTF8))
        self.plane_groupBox.setObjectName(_fromUtf8("plane_groupBox"))
        self.DDirection_0_label = QtGui.QLabel(self.plane_groupBox)
        self.DDirection_0_label.setGeometry(QtCore.QRect(75, 50, 21, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DDirection_0_label.setFont(font)
        self.DDirection_0_label.setText(QtGui.QApplication.translate("MainWindow", "0°", None, QtGui.QApplication.UnicodeUTF8))
        self.DDirection_0_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DDirection_0_label.setObjectName(_fromUtf8("DDirection_0_label"))
        self.DDirection_label = QtGui.QLabel(self.plane_groupBox)
        self.DDirection_label.setGeometry(QtCore.QRect(40, 30, 87, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.DDirection_label.setFont(font)
        self.DDirection_label.setText(QtGui.QApplication.translate("MainWindow", "Dip direction", None, QtGui.QApplication.UnicodeUTF8))
        self.DDirection_label.setObjectName(_fromUtf8("DDirection_label"))
        self.DAngle_label = QtGui.QLabel(self.plane_groupBox)
        self.DAngle_label.setGeometry(QtCore.QRect(160, 30, 63, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.DAngle_label.setFont(font)
        self.DAngle_label.setText(QtGui.QApplication.translate("MainWindow", "Dip angle", None, QtGui.QApplication.UnicodeUTF8))
        self.DAngle_label.setObjectName(_fromUtf8("DAngle_label"))
        self.DDirection_90_label = QtGui.QLabel(self.plane_groupBox)
        self.DDirection_90_label.setGeometry(QtCore.QRect(140, 115, 30, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DDirection_90_label.setFont(font)
        self.DDirection_90_label.setText(QtGui.QApplication.translate("MainWindow", "90°", None, QtGui.QApplication.UnicodeUTF8))
        self.DDirection_90_label.setObjectName(_fromUtf8("DDirection_90_label"))
        self.DDirection_spinBox = QtGui.QSpinBox(self.plane_groupBox)
        self.DDirection_spinBox.setGeometry(QtCore.QRect(65, 204, 54, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DDirection_spinBox.setFont(font)
        self.DDirection_spinBox.setMinimum(0)
        self.DDirection_spinBox.setMaximum(360)
        self.DDirection_spinBox.setSingleStep(1)
        self.DDirection_spinBox.setObjectName(_fromUtf8("DDirection_spinBox"))
        self.DDirection_dial = QtGui.QDial(self.plane_groupBox)
        self.DDirection_dial.setGeometry(QtCore.QRect(35, 70, 100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DDirection_dial.setFont(font)
        self.DDirection_dial.setMaximum(359)
        self.DDirection_dial.setPageStep(30)
        self.DDirection_dial.setProperty("value", 180)
        self.DDirection_dial.setSliderPosition(180)
        self.DDirection_dial.setTracking(True)
        self.DDirection_dial.setOrientation(QtCore.Qt.Vertical)
        self.DDirection_dial.setInvertedAppearance(False)
        self.DDirection_dial.setInvertedControls(False)
        self.DDirection_dial.setWrapping(True)
        self.DDirection_dial.setNotchTarget(10.0)
        self.DDirection_dial.setNotchesVisible(True)
        self.DDirection_dial.setObjectName(_fromUtf8("DDirection_dial"))
        self.DAngle_verticalSlider = QtGui.QSlider(self.plane_groupBox)
        self.DAngle_verticalSlider.setGeometry(QtCore.QRect(181, 59, 21, 124))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DAngle_verticalSlider.setFont(font)
        self.DAngle_verticalSlider.setMaximum(90)
        self.DAngle_verticalSlider.setProperty("value", 45)
        self.DAngle_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.DAngle_verticalSlider.setInvertedAppearance(True)
        self.DAngle_verticalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.DAngle_verticalSlider.setTickInterval(15)
        self.DAngle_verticalSlider.setObjectName(_fromUtf8("DAngle_verticalSlider"))
        self.DDirection_180_label = QtGui.QLabel(self.plane_groupBox)
        self.DDirection_180_label.setGeometry(QtCore.QRect(75, 175, 33, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DDirection_180_label.setFont(font)
        self.DDirection_180_label.setText(QtGui.QApplication.translate("MainWindow", "180°", None, QtGui.QApplication.UnicodeUTF8))
        self.DDirection_180_label.setObjectName(_fromUtf8("DDirection_180_label"))
        self.DAngle_spinBox = QtGui.QSpinBox(self.plane_groupBox)
        self.DAngle_spinBox.setGeometry(QtCore.QRect(175, 205, 43, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DAngle_spinBox.setFont(font)
        self.DAngle_spinBox.setMinimum(0)
        self.DAngle_spinBox.setMaximum(90)
        self.DAngle_spinBox.setSingleStep(1)
        self.DAngle_spinBox.setProperty("value", 45)
        self.DAngle_spinBox.setObjectName(_fromUtf8("DAngle_spinBox"))
        self.DDirection_270_label = QtGui.QLabel(self.plane_groupBox)
        self.DDirection_270_label.setGeometry(QtCore.QRect(5, 115, 37, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DDirection_270_label.setFont(font)
        self.DDirection_270_label.setText(QtGui.QApplication.translate("MainWindow", "270°", None, QtGui.QApplication.UnicodeUTF8))
        self.DDirection_270_label.setObjectName(_fromUtf8("DDirection_270_label"))
        self.DAngle_90_label = QtGui.QLabel(self.plane_groupBox)
        self.DAngle_90_label.setGeometry(QtCore.QRect(215, 55, 21, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DAngle_90_label.setFont(font)
        self.DAngle_90_label.setText(QtGui.QApplication.translate("MainWindow", "0°", None, QtGui.QApplication.UnicodeUTF8))
        self.DAngle_90_label.setObjectName(_fromUtf8("DAngle_90_label"))
        self.DDirection_45_label = QtGui.QLabel(self.plane_groupBox)
        self.DDirection_45_label.setGeometry(QtCore.QRect(209, 115, 25, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DDirection_45_label.setFont(font)
        self.DDirection_45_label.setText(QtGui.QApplication.translate("MainWindow", "45°", None, QtGui.QApplication.UnicodeUTF8))
        self.DDirection_45_label.setObjectName(_fromUtf8("DDirection_45_label"))
        self.DAngle_0_label = QtGui.QLabel(self.plane_groupBox)
        self.DAngle_0_label.setGeometry(QtCore.QRect(209, 170, 24, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.DAngle_0_label.setFont(font)
        self.DAngle_0_label.setText(QtGui.QApplication.translate("MainWindow", "90°", None, QtGui.QApplication.UnicodeUTF8))
        self.DAngle_0_label.setObjectName(_fromUtf8("DAngle_0_label"))
        self.Intersection_widget = QtGui.QWidget(self.centralwidget)
        self.Intersection_widget.setGeometry(QtCore.QRect(5, 550, 251, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Intersection_widget.setFont(font)
        self.Intersection_widget.setObjectName(_fromUtf8("Intersection_widget"))
        self.groupBox = QtGui.QGroupBox(self.Intersection_widget)
        self.groupBox.setGeometry(QtCore.QRect(9, 10, 238, 93))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Intersections", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.Intersection_calculate_pushButton = QtGui.QPushButton(self.groupBox)
        self.Intersection_calculate_pushButton.setGeometry(QtCore.QRect(65, 28, 75, 23))
        self.Intersection_calculate_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.Intersection_calculate_pushButton.setObjectName(_fromUtf8("Intersection_calculate_pushButton"))
        self.Intersection_color_comboBox = QtGui.QComboBox(self.groupBox)
        self.Intersection_color_comboBox.setGeometry(QtCore.QRect(97, 66, 66, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Intersection_color_comboBox.setFont(font)
        self.Intersection_color_comboBox.setObjectName(_fromUtf8("Intersection_color_comboBox"))
        self.Intersection_color_comboBox.addItem(_fromUtf8(""))
        self.Intersection_color_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "white", None, QtGui.QApplication.UnicodeUTF8))
        self.Intersection_color_comboBox.addItem(_fromUtf8(""))
        self.Intersection_color_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.Intersection_color_comboBox.addItem(_fromUtf8(""))
        self.Intersection_color_comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.Intersection_color_comboBox.addItem(_fromUtf8(""))
        self.Intersection_color_comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.Intersection_color_comboBox.addItem(_fromUtf8(""))
        self.Intersection_color_comboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "orange", None, QtGui.QApplication.UnicodeUTF8))
        self.Intersection_color_comboBox.addItem(_fromUtf8(""))
        self.Intersection_color_comboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "brown", None, QtGui.QApplication.UnicodeUTF8))
        self.Intersection_show_checkBox = QtGui.QCheckBox(self.groupBox)
        self.Intersection_show_checkBox.setGeometry(QtCore.QRect(175, 67, 52, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.Intersection_show_checkBox.setFont(font)
        self.Intersection_show_checkBox.setText(QtGui.QApplication.translate("MainWindow", "show", None, QtGui.QApplication.UnicodeUTF8))
        self.Intersection_show_checkBox.setChecked(True)
        self.Intersection_show_checkBox.setObjectName(_fromUtf8("Intersection_show_checkBox"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave_solution_as = QtGui.QMenu(self.menuFile)
        self.menuSave_solution_as.setTitle(QtGui.QApplication.translate("MainWindow", "Save solution as ..", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave_solution_as.setObjectName(_fromUtf8("menuSave_solution_as"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionInput_DEM = QtGui.QAction(MainWindow)
        self.actionInput_DEM.setText(QtGui.QApplication.translate("MainWindow", "Input &DEM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInput_DEM.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInput_DEM.setObjectName(_fromUtf8("actionInput_DEM"))
        self.actionInput_line_shapefile = QtGui.QAction(MainWindow)
        self.actionInput_line_shapefile.setText(QtGui.QApplication.translate("MainWindow", "Input line shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInput_line_shapefile.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInput_line_shapefile.setObjectName(_fromUtf8("actionInput_line_shapefile"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionPoints = QtGui.QAction(MainWindow)
        self.actionPoints.setText(QtGui.QApplication.translate("MainWindow", "points", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPoints.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPoints.setObjectName(_fromUtf8("actionPoints"))
        self.actionLines = QtGui.QAction(MainWindow)
        self.actionLines.setText(QtGui.QApplication.translate("MainWindow", "lines", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLines.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLines.setObjectName(_fromUtf8("actionLines"))
        self.menuSave_solution_as.addAction(self.actionPoints)
        self.menuSave_solution_as.addAction(self.actionLines)
        self.menuFile.addAction(self.actionInput_DEM)
        self.menuFile.addAction(self.actionInput_line_shapefile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSave_solution_as.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.Fault_label.setBuddy(self.Trace_lineEdit)
        self.DEM_label.setBuddy(self.DEM_lineEdit)
        self.DEM_cmap_label.setBuddy(self.DEM_cmap_comboBox)
        self.Pt_label_x.setBuddy(self.Pt_spinBox_x)
        self.Pt_label_y.setBuddy(self.Pt_spinBox_y)
        self.Pt_label_z.setBuddy(self.Pt_spinBox_z)
        self.DDirection_0_label.setBuddy(self.DDirection_dial)
        self.DDirection_label.setBuddy(self.DDirection_dial)
        self.DAngle_label.setBuddy(self.DAngle_verticalSlider)
        self.DDirection_90_label.setBuddy(self.DDirection_dial)
        self.DDirection_180_label.setBuddy(self.DDirection_dial)
        self.DDirection_270_label.setBuddy(self.DDirection_dial)
        self.DDirection_45_label.setBuddy(self.DAngle_verticalSlider)
        self.DAngle_0_label.setBuddy(self.DAngle_verticalSlider)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.DEM_lineEdit, self.show_DEM_checkBox)
        MainWindow.setTabOrder(self.show_DEM_checkBox, self.Trace_lineEdit)
        MainWindow.setTabOrder(self.Trace_lineEdit, self.show_Fault_checkBox)
        MainWindow.setTabOrder(self.show_Fault_checkBox, self.DEM_cmap_comboBox)
        MainWindow.setTabOrder(self.DEM_cmap_comboBox, self.show_SrcPt_checkBox)
        MainWindow.setTabOrder(self.show_SrcPt_checkBox, self.Pt_spinBox_x)
        MainWindow.setTabOrder(self.Pt_spinBox_x, self.Pt_spinBox_y)
        MainWindow.setTabOrder(self.Pt_spinBox_y, self.Pt_spinBox_z)
        MainWindow.setTabOrder(self.Pt_spinBox_z, self.Z_fix2DEM_checkBox_z)
        MainWindow.setTabOrder(self.Z_fix2DEM_checkBox_z, self.DDirection_dial)
        MainWindow.setTabOrder(self.DDirection_dial, self.DDirection_spinBox)
        MainWindow.setTabOrder(self.DDirection_spinBox, self.DAngle_verticalSlider)
        MainWindow.setTabOrder(self.DAngle_verticalSlider, self.DAngle_spinBox)
        MainWindow.setTabOrder(self.DAngle_spinBox, self.Intersection_show_checkBox)
        MainWindow.setTabOrder(self.Intersection_show_checkBox, self.Intersection_color_comboBox)

    def retranslateUi(self, MainWindow):
        pass

from gSurf_mplwidget import MplWidget
