# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gSurf_0.2.0.1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 708)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mplwidget = MplWidget(self.centralwidget)
        self.mplwidget.setGeometry(QtCore.QRect(260, 5, 730, 655))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget.sizePolicy().hasHeightForWidth())
        self.mplwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.mplwidget.setFont(font)
        self.mplwidget.setObjectName("mplwidget")
        self.Input_widget = QtWidgets.QWidget(self.centralwidget)
        self.Input_widget.setGeometry(QtCore.QRect(5, 6, 251, 138))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Input_widget.setFont(font)
        self.Input_widget.setObjectName("Input_widget")
        self.input_groupBox = QtWidgets.QGroupBox(self.Input_widget)
        self.input_groupBox.setGeometry(QtCore.QRect(10, 5, 236, 128))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.input_groupBox.setFont(font)
        self.input_groupBox.setObjectName("input_groupBox")
        self.show_label = QtWidgets.QLabel(self.input_groupBox)
        self.show_label.setGeometry(QtCore.QRect(195, 18, 30, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.show_label.setFont(font)
        self.show_label.setObjectName("show_label")
        self.layoutWidget = QtWidgets.QWidget(self.input_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 36, 213, 64))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.show_Fault_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.show_Fault_checkBox.setFont(font)
        self.show_Fault_checkBox.setText("")
        self.show_Fault_checkBox.setChecked(True)
        self.show_Fault_checkBox.setObjectName("show_Fault_checkBox")
        self.gridLayout.addWidget(self.show_Fault_checkBox, 1, 2, 1, 1)
        self.Trace_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Trace_lineEdit.setFont(font)
        self.Trace_lineEdit.setReadOnly(True)
        self.Trace_lineEdit.setObjectName("Trace_lineEdit")
        self.gridLayout.addWidget(self.Trace_lineEdit, 1, 1, 1, 1)
        self.show_DEM_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.show_DEM_checkBox.setFont(font)
        self.show_DEM_checkBox.setText("")
        self.show_DEM_checkBox.setChecked(True)
        self.show_DEM_checkBox.setObjectName("show_DEM_checkBox")
        self.gridLayout.addWidget(self.show_DEM_checkBox, 0, 2, 1, 1)
        self.DEM_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DEM_lineEdit.setFont(font)
        self.DEM_lineEdit.setReadOnly(True)
        self.DEM_lineEdit.setObjectName("DEM_lineEdit")
        self.gridLayout.addWidget(self.DEM_lineEdit, 0, 1, 1, 1)
        self.Fault_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Fault_label.setFont(font)
        self.Fault_label.setObjectName("Fault_label")
        self.gridLayout.addWidget(self.Fault_label, 1, 0, 1, 1)
        self.DEM_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DEM_label.setFont(font)
        self.DEM_label.setObjectName("DEM_label")
        self.gridLayout.addWidget(self.DEM_label, 0, 0, 1, 1)
        self.DEM_cmap_label = QtWidgets.QLabel(self.input_groupBox)
        self.DEM_cmap_label.setGeometry(QtCore.QRect(10, 103, 95, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DEM_cmap_label.setFont(font)
        self.DEM_cmap_label.setObjectName("DEM_cmap_label")
        self.DEM_cmap_comboBox = QtWidgets.QComboBox(self.input_groupBox)
        self.DEM_cmap_comboBox.setGeometry(QtCore.QRect(107, 100, 98, 22))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DEM_cmap_comboBox.setFont(font)
        self.DEM_cmap_comboBox.setObjectName("DEM_cmap_comboBox")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.DEM_cmap_comboBox.addItem("")
        self.SourcePoint_widget = QtWidgets.QWidget(self.centralwidget)
        self.SourcePoint_widget.setGeometry(QtCore.QRect(5, 148, 251, 130))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.SourcePoint_widget.setFont(font)
        self.SourcePoint_widget.setObjectName("SourcePoint_widget")
        self.point_groupBox = QtWidgets.QGroupBox(self.SourcePoint_widget)
        self.point_groupBox.setGeometry(QtCore.QRect(10, 2, 236, 121))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.point_groupBox.setFont(font)
        self.point_groupBox.setObjectName("point_groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.point_groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 127, 98))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Pt_label_x = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Pt_label_x.setFont(font)
        self.Pt_label_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Pt_label_x.setObjectName("Pt_label_x")
        self.gridLayout_2.addWidget(self.Pt_label_x, 0, 0, 1, 1)
        self.Pt_spinBox_x = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Pt_spinBox_x.setFont(font)
        self.Pt_spinBox_x.setMinimum(-1000000000)
        self.Pt_spinBox_x.setMaximum(1000000000)
        self.Pt_spinBox_x.setSingleStep(50)
        self.Pt_spinBox_x.setObjectName("Pt_spinBox_x")
        self.gridLayout_2.addWidget(self.Pt_spinBox_x, 0, 1, 1, 1)
        self.Pt_label_y = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Pt_label_y.setFont(font)
        self.Pt_label_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Pt_label_y.setObjectName("Pt_label_y")
        self.gridLayout_2.addWidget(self.Pt_label_y, 1, 0, 1, 1)
        self.Pt_spinBox_y = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Pt_spinBox_y.setFont(font)
        self.Pt_spinBox_y.setMinimum(-1000000000)
        self.Pt_spinBox_y.setMaximum(1000000000)
        self.Pt_spinBox_y.setSingleStep(50)
        self.Pt_spinBox_y.setObjectName("Pt_spinBox_y")
        self.gridLayout_2.addWidget(self.Pt_spinBox_y, 1, 1, 1, 1)
        self.Pt_label_z = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Pt_label_z.setFont(font)
        self.Pt_label_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Pt_label_z.setObjectName("Pt_label_z")
        self.gridLayout_2.addWidget(self.Pt_label_z, 2, 0, 1, 1)
        self.Pt_spinBox_z = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Pt_spinBox_z.setFont(font)
        self.Pt_spinBox_z.setMinimum(-10000000)
        self.Pt_spinBox_z.setMaximum(10000000)
        self.Pt_spinBox_z.setSingleStep(5)
        self.Pt_spinBox_z.setObjectName("Pt_spinBox_z")
        self.gridLayout_2.addWidget(self.Pt_spinBox_z, 2, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.point_groupBox)
        self.splitter.setGeometry(QtCore.QRect(145, 42, 86, 64))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.show_SrcPt_checkBox = QtWidgets.QCheckBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.show_SrcPt_checkBox.setFont(font)
        self.show_SrcPt_checkBox.setChecked(True)
        self.show_SrcPt_checkBox.setObjectName("show_SrcPt_checkBox")
        self.Z_fix2DEM_checkBox_z = QtWidgets.QCheckBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Z_fix2DEM_checkBox_z.setFont(font)
        self.Z_fix2DEM_checkBox_z.setChecked(True)
        self.Z_fix2DEM_checkBox_z.setObjectName("Z_fix2DEM_checkBox_z")
        self.Plane_widget = QtWidgets.QWidget(self.centralwidget)
        self.Plane_widget.setGeometry(QtCore.QRect(5, 285, 252, 253))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Plane_widget.setFont(font)
        self.Plane_widget.setObjectName("Plane_widget")
        self.plane_groupBox = QtWidgets.QGroupBox(self.Plane_widget)
        self.plane_groupBox.setGeometry(QtCore.QRect(10, 5, 237, 242))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.plane_groupBox.setFont(font)
        self.plane_groupBox.setObjectName("plane_groupBox")
        self.DDirection_0_label = QtWidgets.QLabel(self.plane_groupBox)
        self.DDirection_0_label.setGeometry(QtCore.QRect(75, 50, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DDirection_0_label.setFont(font)
        self.DDirection_0_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DDirection_0_label.setObjectName("DDirection_0_label")
        self.DDirection_label = QtWidgets.QLabel(self.plane_groupBox)
        self.DDirection_label.setGeometry(QtCore.QRect(40, 30, 87, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.DDirection_label.setFont(font)
        self.DDirection_label.setObjectName("DDirection_label")
        self.DAngle_label = QtWidgets.QLabel(self.plane_groupBox)
        self.DAngle_label.setGeometry(QtCore.QRect(160, 30, 63, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.DAngle_label.setFont(font)
        self.DAngle_label.setObjectName("DAngle_label")
        self.DDirection_90_label = QtWidgets.QLabel(self.plane_groupBox)
        self.DDirection_90_label.setGeometry(QtCore.QRect(140, 115, 30, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DDirection_90_label.setFont(font)
        self.DDirection_90_label.setObjectName("DDirection_90_label")
        self.DDirection_spinBox = QtWidgets.QSpinBox(self.plane_groupBox)
        self.DDirection_spinBox.setGeometry(QtCore.QRect(65, 204, 54, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DDirection_spinBox.setFont(font)
        self.DDirection_spinBox.setMinimum(0)
        self.DDirection_spinBox.setMaximum(360)
        self.DDirection_spinBox.setSingleStep(1)
        self.DDirection_spinBox.setObjectName("DDirection_spinBox")
        self.DDirection_dial = QtWidgets.QDial(self.plane_groupBox)
        self.DDirection_dial.setGeometry(QtCore.QRect(35, 70, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DDirection_dial.setFont(font)
        self.DDirection_dial.setMaximum(359)
        self.DDirection_dial.setPageStep(30)
        self.DDirection_dial.setProperty("value", 180)
        self.DDirection_dial.setSliderPosition(180)
        self.DDirection_dial.setTracking(True)
        self.DDirection_dial.setOrientation(QtCore.Qt.Vertical)
        self.DDirection_dial.setInvertedAppearance(False)
        self.DDirection_dial.setInvertedControls(False)
        self.DDirection_dial.setWrapping(True)
        self.DDirection_dial.setNotchTarget(10.0)
        self.DDirection_dial.setNotchesVisible(True)
        self.DDirection_dial.setObjectName("DDirection_dial")
        self.DAngle_verticalSlider = QtWidgets.QSlider(self.plane_groupBox)
        self.DAngle_verticalSlider.setGeometry(QtCore.QRect(181, 59, 21, 124))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DAngle_verticalSlider.setFont(font)
        self.DAngle_verticalSlider.setMaximum(90)
        self.DAngle_verticalSlider.setProperty("value", 45)
        self.DAngle_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.DAngle_verticalSlider.setInvertedAppearance(True)
        self.DAngle_verticalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.DAngle_verticalSlider.setTickInterval(15)
        self.DAngle_verticalSlider.setObjectName("DAngle_verticalSlider")
        self.DDirection_180_label = QtWidgets.QLabel(self.plane_groupBox)
        self.DDirection_180_label.setGeometry(QtCore.QRect(75, 175, 33, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DDirection_180_label.setFont(font)
        self.DDirection_180_label.setObjectName("DDirection_180_label")
        self.DAngle_spinBox = QtWidgets.QSpinBox(self.plane_groupBox)
        self.DAngle_spinBox.setGeometry(QtCore.QRect(175, 205, 43, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DAngle_spinBox.setFont(font)
        self.DAngle_spinBox.setMinimum(0)
        self.DAngle_spinBox.setMaximum(90)
        self.DAngle_spinBox.setSingleStep(1)
        self.DAngle_spinBox.setProperty("value", 45)
        self.DAngle_spinBox.setObjectName("DAngle_spinBox")
        self.DDirection_270_label = QtWidgets.QLabel(self.plane_groupBox)
        self.DDirection_270_label.setGeometry(QtCore.QRect(5, 115, 37, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DDirection_270_label.setFont(font)
        self.DDirection_270_label.setObjectName("DDirection_270_label")
        self.DAngle_90_label = QtWidgets.QLabel(self.plane_groupBox)
        self.DAngle_90_label.setGeometry(QtCore.QRect(215, 55, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DAngle_90_label.setFont(font)
        self.DAngle_90_label.setObjectName("DAngle_90_label")
        self.DDirection_45_label = QtWidgets.QLabel(self.plane_groupBox)
        self.DDirection_45_label.setGeometry(QtCore.QRect(209, 115, 25, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DDirection_45_label.setFont(font)
        self.DDirection_45_label.setObjectName("DDirection_45_label")
        self.DAngle_0_label = QtWidgets.QLabel(self.plane_groupBox)
        self.DAngle_0_label.setGeometry(QtCore.QRect(209, 170, 24, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.DAngle_0_label.setFont(font)
        self.DAngle_0_label.setObjectName("DAngle_0_label")
        self.Intersection_widget = QtWidgets.QWidget(self.centralwidget)
        self.Intersection_widget.setGeometry(QtCore.QRect(5, 550, 251, 111))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Intersection_widget.setFont(font)
        self.Intersection_widget.setObjectName("Intersection_widget")
        self.groupBox = QtWidgets.QGroupBox(self.Intersection_widget)
        self.groupBox.setGeometry(QtCore.QRect(9, 10, 238, 93))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.Intersection_calculate_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.Intersection_calculate_pushButton.setGeometry(QtCore.QRect(65, 28, 75, 23))
        self.Intersection_calculate_pushButton.setObjectName("Intersection_calculate_pushButton")
        self.Intersection_color_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.Intersection_color_comboBox.setGeometry(QtCore.QRect(97, 66, 66, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Intersection_color_comboBox.setFont(font)
        self.Intersection_color_comboBox.setObjectName("Intersection_color_comboBox")
        self.Intersection_color_comboBox.addItem("")
        self.Intersection_color_comboBox.addItem("")
        self.Intersection_color_comboBox.addItem("")
        self.Intersection_color_comboBox.addItem("")
        self.Intersection_color_comboBox.addItem("")
        self.Intersection_color_comboBox.addItem("")
        self.Intersection_show_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.Intersection_show_checkBox.setGeometry(QtCore.QRect(175, 67, 52, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.Intersection_show_checkBox.setFont(font)
        self.Intersection_show_checkBox.setChecked(True)
        self.Intersection_show_checkBox.setObjectName("Intersection_show_checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave_solution_as = QtWidgets.QMenu(self.menuFile)
        self.menuSave_solution_as.setObjectName("menuSave_solution_as")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInput_DEM = QtWidgets.QAction(MainWindow)
        self.actionInput_DEM.setObjectName("actionInput_DEM")
        self.actionInput_line_shapefile = QtWidgets.QAction(MainWindow)
        self.actionInput_line_shapefile.setObjectName("actionInput_line_shapefile")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPoints = QtWidgets.QAction(MainWindow)
        self.actionPoints.setObjectName("actionPoints")
        self.actionLines = QtWidgets.QAction(MainWindow)
        self.actionLines.setObjectName("actionLines")
        self.menuSave_solution_as.addAction(self.actionPoints)
        self.menuSave_solution_as.addAction(self.actionLines)
        self.menuFile.addAction(self.actionInput_DEM)
        self.menuFile.addAction(self.actionInput_line_shapefile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSave_solution_as.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.Fault_label.setBuddy(self.Trace_lineEdit)
        self.DEM_label.setBuddy(self.DEM_lineEdit)
        self.DEM_cmap_label.setBuddy(self.DEM_cmap_comboBox)
        self.Pt_label_x.setBuddy(self.Pt_spinBox_x)
        self.Pt_label_y.setBuddy(self.Pt_spinBox_y)
        self.Pt_label_z.setBuddy(self.Pt_spinBox_z)
        self.DDirection_0_label.setBuddy(self.DDirection_dial)
        self.DDirection_label.setBuddy(self.DDirection_dial)
        self.DAngle_label.setBuddy(self.DAngle_verticalSlider)
        self.DDirection_90_label.setBuddy(self.DDirection_dial)
        self.DDirection_180_label.setBuddy(self.DDirection_dial)
        self.DDirection_270_label.setBuddy(self.DDirection_dial)
        self.DDirection_45_label.setBuddy(self.DAngle_verticalSlider)
        self.DAngle_0_label.setBuddy(self.DAngle_verticalSlider)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.DEM_lineEdit, self.show_DEM_checkBox)
        MainWindow.setTabOrder(self.show_DEM_checkBox, self.Trace_lineEdit)
        MainWindow.setTabOrder(self.Trace_lineEdit, self.show_Fault_checkBox)
        MainWindow.setTabOrder(self.show_Fault_checkBox, self.DEM_cmap_comboBox)
        MainWindow.setTabOrder(self.DEM_cmap_comboBox, self.show_SrcPt_checkBox)
        MainWindow.setTabOrder(self.show_SrcPt_checkBox, self.Pt_spinBox_x)
        MainWindow.setTabOrder(self.Pt_spinBox_x, self.Pt_spinBox_y)
        MainWindow.setTabOrder(self.Pt_spinBox_y, self.Pt_spinBox_z)
        MainWindow.setTabOrder(self.Pt_spinBox_z, self.Z_fix2DEM_checkBox_z)
        MainWindow.setTabOrder(self.Z_fix2DEM_checkBox_z, self.DDirection_dial)
        MainWindow.setTabOrder(self.DDirection_dial, self.DDirection_spinBox)
        MainWindow.setTabOrder(self.DDirection_spinBox, self.DAngle_verticalSlider)
        MainWindow.setTabOrder(self.DAngle_verticalSlider, self.DAngle_spinBox)
        MainWindow.setTabOrder(self.DAngle_spinBox, self.Intersection_show_checkBox)
        MainWindow.setTabOrder(self.Intersection_show_checkBox, self.Intersection_color_comboBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "gSurf   -  vers. 0.2.0"))
        self.input_groupBox.setTitle(_translate("MainWindow", "Input layers"))
        self.show_label.setText(_translate("MainWindow", "show"))
        self.Trace_lineEdit.setPlaceholderText(_translate("MainWindow", "optional"))
        self.DEM_lineEdit.setPlaceholderText(_translate("MainWindow", "required"))
        self.Fault_label.setText(_translate("MainWindow", "Faults"))
        self.DEM_label.setText(_translate("MainWindow", "DE&M"))
        self.DEM_cmap_label.setText(_translate("MainWindow", "DEM colormap"))
        self.DEM_cmap_comboBox.setItemText(0, _translate("MainWindow", "jet"))
        self.DEM_cmap_comboBox.setItemText(1, _translate("MainWindow", "gray"))
        self.DEM_cmap_comboBox.setItemText(2, _translate("MainWindow", "bone"))
        self.DEM_cmap_comboBox.setItemText(3, _translate("MainWindow", "hot"))
        self.DEM_cmap_comboBox.setItemText(4, _translate("MainWindow", "autumn"))
        self.DEM_cmap_comboBox.setItemText(5, _translate("MainWindow", "cool"))
        self.DEM_cmap_comboBox.setItemText(6, _translate("MainWindow", "copper"))
        self.DEM_cmap_comboBox.setItemText(7, _translate("MainWindow", "hsv"))
        self.DEM_cmap_comboBox.setItemText(8, _translate("MainWindow", "pink"))
        self.DEM_cmap_comboBox.setItemText(9, _translate("MainWindow", "prism"))
        self.DEM_cmap_comboBox.setItemText(10, _translate("MainWindow", "spring"))
        self.DEM_cmap_comboBox.setItemText(11, _translate("MainWindow", "summer"))
        self.DEM_cmap_comboBox.setItemText(12, _translate("MainWindow", "winter"))
        self.DEM_cmap_comboBox.setItemText(13, _translate("MainWindow", "spectral"))
        self.DEM_cmap_comboBox.setItemText(14, _translate("MainWindow", "flag"))
        self.point_groupBox.setTitle(_translate("MainWindow", "Plane source point"))
        self.Pt_label_x.setText(_translate("MainWindow", "&X"))
        self.Pt_label_y.setText(_translate("MainWindow", "Y"))
        self.Pt_label_z.setText(_translate("MainWindow", "&Z"))
        self.show_SrcPt_checkBox.setText(_translate("MainWindow", "show"))
        self.Z_fix2DEM_checkBox_z.setText(_translate("MainWindow", "fix  to DEM"))
        self.plane_groupBox.setTitle(_translate("MainWindow", "Plane attitude"))
        self.DDirection_0_label.setText(_translate("MainWindow", "&0°"))
        self.DDirection_label.setText(_translate("MainWindow", "Dip direction"))
        self.DAngle_label.setText(_translate("MainWindow", "Dip angle"))
        self.DDirection_90_label.setText(_translate("MainWindow", "&90°"))
        self.DDirection_180_label.setText(_translate("MainWindow", "&180°"))
        self.DDirection_270_label.setText(_translate("MainWindow", "&270°"))
        self.DAngle_90_label.setText(_translate("MainWindow", "0°"))
        self.DDirection_45_label.setText(_translate("MainWindow", "&45°"))
        self.DAngle_0_label.setText(_translate("MainWindow", "90°"))
        self.groupBox.setTitle(_translate("MainWindow", "Intersections"))
        self.Intersection_calculate_pushButton.setText(_translate("MainWindow", "Calculate"))
        self.Intersection_color_comboBox.setItemText(0, _translate("MainWindow", "white"))
        self.Intersection_color_comboBox.setItemText(1, _translate("MainWindow", "red"))
        self.Intersection_color_comboBox.setItemText(2, _translate("MainWindow", "blue"))
        self.Intersection_color_comboBox.setItemText(3, _translate("MainWindow", "yellow"))
        self.Intersection_color_comboBox.setItemText(4, _translate("MainWindow", "orange"))
        self.Intersection_color_comboBox.setItemText(5, _translate("MainWindow", "brown"))
        self.Intersection_show_checkBox.setText(_translate("MainWindow", "show"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuSave_solution_as.setTitle(_translate("MainWindow", "&Save solution as .."))
        self.menuHelp.setTitle(_translate("MainWindow", "&Info"))
        self.actionInput_DEM.setText(_translate("MainWindow", "Input &DEM"))
        self.actionInput_DEM.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionInput_line_shapefile.setText(_translate("MainWindow", "&Input line shapefile"))
        self.actionInput_line_shapefile.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionHelp.setText(_translate("MainWindow", "&Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionPoints.setText(_translate("MainWindow", "&points"))
        self.actionPoints.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionLines.setText(_translate("MainWindow", "&lines"))
        self.actionLines.setShortcut(_translate("MainWindow", "Ctrl+L"))

from gSurf_mplwidget import MplWidget
